# TODO: maybe use Spring Profiles so have separate configs for local vs Production
logging:
  level:
    com.example.springboot: DEBUG

server.servlet.contextPath: /api/v1

marvel.api.public.key: your_public_key
marvel.api.private.key: your_private_key
