# TODO: maybe use Spring Profiles so have separate configs for local vs Production
logging:
  level:
    com.example.springboot: DEBUG


spring.datasource.url: jdbc:postgresql://localhost:5432/marvel-db
spring.datasource.username: marvel-user
spring.datasource.password: marvel-pass

spring:
  flyway:
    locations: classpath:db/migrations
    schemas:
      - marvel
    create-schemas: true

server.servlet.contextPath: /api/v1

marvel.api.public.key: your_public_key
marvel.api.private.key: your_private_key
